[workspace]
members = [
    "air",
    "assembly",
    "core",
    "miden",
    "processor",
    "prover",
    "stdlib",
    "test-utils",
    "verifier",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.82"
license = "MIT"
readme = "README.md"
authors = ["Miden contributors"]
homepage = "https://polygon.technology/polygon-miden"
repository = "https://github.com/0xPolygonMiden/miden-vm"
exclude = [".github/"]

[profile.optimized]
inherits = "release"
codegen-units = 1
lto = true

[profile.test-release]
inherits = "release"
debug = true
debug-assertions = true
overflow-checks = true


[patch.crates-io]
winter-air = {git = 'https://github.com/Al-Kindi-0/winterfell', branch = 'al-zk', package = 'winter-air'   }
winter-crypto = {git = 'https://github.com/Al-Kindi-0/winterfell', branch = 'al-zk', package = 'winter-crypto'  }
winter-prover = {git = 'https://github.com/Al-Kindi-0/winterfell', branch = 'al-zk', package = 'winter-prover'  }
winter-verifier = { git = 'https://github.com/Al-Kindi-0/winterfell', branch = 'al-zk', package = 'winter-verifier'  }
winter-math = {git = 'https://github.com/Al-Kindi-0/winterfell', branch = 'al-zk', package = 'winter-math'  }
winter-fri = {git = 'https://github.com/Al-Kindi-0/winterfell', branch = 'al-zk', package = 'winter-fri'  }
winter-maybe-async = {git = 'https://github.com/Al-Kindi-0/winterfell', branch = 'al-zk', package = 'winter-maybe-async'  }
winter-utils = {git = 'https://github.com/Al-Kindi-0/winterfell', branch = 'al-zk', package = 'winter-utils'  }
winter-rand-utils = {git = 'https://github.com/Al-Kindi-0/winterfell', branch = 'al-zk', package = 'winter-rand-utils'  }

miden-crypto = {git = 'https://github.com/0xPolygonMiden/crypto', branch = 'al-stark-signature-dev-masm' }
